lectures:
  - front/07-http-ajax

lecture:
  fr:
    video: 154308534

livecode:
  fr:
    video: 136207523
    gist: 7e6c32b50e574c604c35




# Cours API-Webhooks
# lectures:
# - front/08-apis-webhooks
# lecture:
#   video: 136206285
#   gist: 3064ccd994f055f76045
# livecode:
#   video: 136225356
#   gist: 3e874c87e1e21dfda018
